### ISSUE TITLE
Web interface

### ISSUE THREAD

**Issue by chrigui** [7LPdWcaW/GrowTracker-Web#1]
hello,
first, i thank you for sharing such a great app!! I am using it on my farm and we love it.
we have a 20 Hectare farm with multiple crops and your app was exactly we needed to keep track of things.

now there is some few questions and issues I would like to address:
1- I noticed there is an addon for the web interface and a repo for the web interface is it updated? 
2- I have 2 agricultural engineers, 1 supervisor and 4 growers that currently use the app. it will be really great if they can sync the work together to create a better communication through the app.
3- create zones, zone dimension or area in m2 or ft. so we can attach the crop to it.
4- Ability to Log environment data like Humidity, Temp, Co2, or a hook to connect to wunderground
5- Set reminders to your self or to team members (if the app has a multi-user functionality.)
6- Setup Tasks for self or other users.

I know this is too much to ask for but this features coming from a real-life usability of the app. 
i hope my feedback is helpful.

Thanks.
Tc.

**Comment by 7LPdWcaW** [comment]
Hi! amazing to see someone with such large scale use my humble app :)

I did start developing a web version of the app a while back but development kinda stagnated due to limitations with storage - I didnt want to have to rely on any backend API or service to keep anonymity, I may pick it up again in the future, but no immediate plans right now.

I could look at creating a 'sync' addon for the app to pull/push to an external server to allow multiple uses - would potentially be quite difficult as you'll have to deal with what happens if someone is changing something at the same time as someone else (a la the Dropbox problem)

Due to the way the app is structured, I dont think zones/dimensions would be applicable, although you can create gardens which you could put the dimensions in the name of, and logging humidity/temp/C02 etc would also be difficult because all the data is attached to a specific plant rather than an environment, although there is a 'temp' field when feeding a plant that is being grown hydroponically.

I've always toyed with the idea of feeding notifications with some smart logic like taking the average day between feedings and setting reminder notifications based on that but never really looked much into it, certainly is a feature I could take another look at. 

Development is quite slow at the moment with it being a personal app for hobbyist growing in between work life etc, but the project is far from dead :)

**Comment by chrigui** [comment]
Thank you for your reply,
can we move this discussion to email, please ?

**Comment by 7LPdWcaW** [comment]
Sure, 7lpdwcaw@gmail.com
